name: Weather Condition Enrichment
language: python
variables:
  - name: weather_input
    inputType: InputTopic
    description: Weather data input topic
    defaultValue: weather-data
    required: true
  - name: solar_input
    inputType: InputTopic
    description: Solar farm data input topic
    defaultValue: solar-farm
    required: true
  - name: output
    inputType: OutputTopic
    description: Enriched data output topic
    defaultValue: enriched-data
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-transformation
