name: Dangerous Condition Detection
language: python
variables:
  - name: input
    inputType: InputTopic
    description: This is the input topic for f1 data
    defaultValue: weather-data
    required: true
  - name: output
    inputType: OutputTopic
    description: This is the output topic for hard braking events
    defaultValue: danger-conditions
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
libraryItemId: event-detection-transformation
