name: Dangerous Condition Detection
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Enriched data input topic
    defaultValue: enriched-data
    required: true
  - name: output
    inputType: OutputTopic
    description: Dangerous conditions output topic
    defaultValue: danger-conditions
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
libraryItemId: event-detection-transformation
