name: Critical Event Detection
language: python
variables:
  - name: input
    inputType: InputTopic
    multiline: false
    description: This is the input topic for enriched data
    defaultValue: enriched-data
    required: true
  - name: output
    inputType: OutputTopic
    multiline: false
    description: This is the output topic for critical danger conditions
    defaultValue: danger_condition
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: quix_function.py
libraryItemId: event-detection-transformation
