name: Weather Condition Enrichment
language: python
variables:
  - name: input
    inputType: InputTopic
    description: Name of the input topic to listen to.
    defaultValue: weather-data
  - name: output
    inputType: OutputTopic
    description: Name of the output topic to write to.
    defaultValue: enriched-data
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-transformation
