name: HTTP API Weather
language: python
variables:
  - name: output
    inputType: OutputTopic
    multiline: false
    description: This is the output topic for weather configuration data
    defaultValue: configuration
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: web-api-gateway
