name: HiveMQ
language: python
variables:
  - name: output
    inputType: OutputTopic
    multiline: false
    description: Name of the output topic to publish to.
    defaultValue: solar-farm
    required: true
  - name: mqtt_topic
    inputType: FreeText
    multiline: false
    description: The root for messages in MQTT, this can be anything
    required: true
  - name: mqtt_server
    inputType: FreeText
    multiline: false
    description: The address of your MQTT server
    required: true
  - name: mqtt_port
    inputType: FreeText
    multiline: false
    description: The port of your MQTT server
    defaultValue: 8883
    required: true
  - name: mqtt_username
    inputType: FreeText
    multiline: false
    description: Username of your MQTT user
  - name: mqtt_password
    inputType: HiddenText
    multiline: false
    description: Password for the MQTT user
  - name: mqtt_version
    inputType: FreeText
    multiline: false
    description: 'MQTT protocol version: 3.1, 3.1.1, 5'
    defaultValue: 3.1.1
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: mqtt_function.py
libraryItemId: hivemq-source
